name: rick_n_morty_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
    androidBuild: flutter build appbundle
    androidApk: flutter build apk
    iosBuild: flutter build ios
    androidFile: open build/app/outputs/bundle/release/
    iosFile: open -a Xcode ios/Runner.xcworkspace
    incrementBuildNumber: update_build_number
    closingMessage: say 'Finalizado'
    errorMessage: say 'Erro'
scripts:
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs
    build_android: $clean & $incrementBuildNumber & $androidBuild & $androidFile & $closingMessage
    build_android_apk: $clean & $incrementBuildNumber & $androidApk & $closingMessage
    build_ios: $clean & $iosBuild & $iosFile & $closingMessage
    build_ios_inc: $clean && $incrementBuildNumber && $iosBuild && $iosFile && $closingMessage

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Functionalities
  asuka: ^2.0.0-nullsafety.3
  dartz: ^0.10.0
  dio_http_cache: ^0.3.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  flutter_mobx: ^2.0.2
  flutter_modular: ^3.4.1+1
  mobx: ^2.0.4
  path_provider: ^2.0.2
  # Connection and storage
  dio: ^4.0.0
  # Design
  cupertino_icons: ^1.0.3
  flutter_screenutil: ^5.0.0+2
  flutter_vector_icons: ^1.0.0
  rive: ^0.7.28

  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.5
  build_runner: ^2.1.2
  mobx_codegen: ^2.0.1+3
  modular_codegen: ^3.0.0
  flutter_modular_test: ^1.0.3
  
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/ani/